import colors from './colors';

const FONT = "EuclidCircularA";

export default {
    h1: {
        fontSize: '35px',
        fontFamily: '"Roboto", sans-serif',
        fontWeight: 500,
        fontStretch: 'normal',
        fontStyle: 'normal',
        lineHeight: 41/35,
        letterSpacing: '-0.66px',
        color: colors.black,
    },
    h2: {
        fontSize: '30px',
        fontFamily: '"Roboto", sans-serif',
        fontWeight: 500,
        fontStretch: 'normal',
        fontStyle: 'normal',
        lineHeight: 1.25,
        letterSpacing: '-0.5px',
        color: colors.black,
    },
    h3: {
        fontSize: '20px',
        fontFamily: '"Roboto", sans-serif',
        fontWeight: 500,
        fontStretch: 'normal',
        fontStyle: 'normal',
        lineHeight: 1.32,
        letterSpacing: 'normal',
        color: colors.black,
    },
    title: {
        fontSize: '18px',
        fontFamily: '"Roboto", sans-serif',
        fontWeight: 300,
        fontStretch: 'normal',
        fontStyle: 'normal',
        lineHeight: 1,
        letterSpacing: 'normal',
        color: colors.black,
    },
    subtitle: {
        fontSize: '15px',
        fontFamily: '"Roboto", sans-serif',
        fontWeight: 500,
        fontStretch: 'normal',
        fontStyle: 'normal',
        lineHeight: 18/15,
        letterSpacing: "-0.015em",
        color: colors.black,
    },
    smallLabel: {
        fontSize: '10px',
        fontFamily: '"Roboto", sans-serif',
        fontWeight: 500,
        fontStretch: 'normal',
        fontStyle: 'normal',
        lineHeight: 12/10,
        letterSpacing: "0.015em",
        color: colors.black,
    },
    smallParagraph: {
        fontSize: '12px',
        fontFamily: '"Roboto", sans-serif',
        fontWeight: 500,
        fontStretch: 'normal',
        fontStyle: 'normal',
        lineHeight: 1,
        letterSpacing: "0.015em",
        color: colors.black,
    },
    smallHeader: {
        fontSize: '12px',
        fontFamily: '"Roboto", sans-serif',
        fontWeight: 500,
        fontStretch: 'normal',
        fontStyle: 'normal',
        lineHeight: 14/12,
        letterSpacing: "0.015em",
        color: colors.black,
    },

};
